### ISSUE TITLE
None of the examples compile

### ISSUE THREAD

**Issue by whyCPPgofast** [PrivateRookie/ws-tool#16]
I just cloned the repo for the first time and none of the examples compile. I see a bunch of things like `unresolved import ws_tool::codec::WsBytesCodec`. Can you re-clone your own repo and see whats going on?

**Comment by whyCPPgofast** [comment]
Its because there is settings file in the .vscode folder with `"rust-analyzer.cargo.allFeatures": true` I switched to rust-analyzer and now it compiles. I wonder how do I enable all features with RLS?

**Comment by whyCPPgofast** [comment]
Still doesn't compile load_test 
```
error[E0599]: no method named `cert` found for struct `ClientBuilder` in the current scope
  --> examples\load_test.rs:40:27
   |
40 |         builder = builder.cert(cert);
   |                           ^^^^ method not found in `ClientBuilder`
```

**Comment by whyCPPgofast** [comment]
There is lots of issues with the examples folder. With rust-analyzer it doesnt show the errors immediately only when you actually try to run it. Using the RLS extension (VSCode)  immediately shows all the compile errors.

**Comment by PrivateRookie** [comment]
ws-tool uses conditional compilation to keep dependencies as few as possible. So if you want to use a custom ssl certificate, you must add the xxx_tls_rustls feature flag at compile time.  For convenience, you can compile with the `--all-features` option,  I also mentioned this usage in the README, 
please read the README document carefully before using it. If you are not familiar with rust, please consult the relevant documentation.

As for RLS,  RA has been declared as an official plugin, please move to RA

**Comment by whyCPPgofast** [comment]
I did not know about `--all-features` but I am familiar with rust.

No I will not be moving to RA because it sucks in projects with multiple binaries.

I still have no idea how benchmarks are supposed to be ran?

Running bench_server.rs just starts a server which is non-intuitive maybe you should add some docs about benchmarks since you are advertising performance.

I ran load_test.rs after and that just outputs a number that I have no idea what it means.

**Comment by PrivateRookie** [comment]
The complete performance test of ws-tool has not been completed, so I use the ready-made test tool provided by uWebSockets [load_test.c](https://github.com/uNetworking/uWebSockets/blob/master/benchmarks/load_test.c), build it with makefile provided by uWebSockets, This file connects to the server as a client, you can start it with `./load_test <client_number> <server_host> <server_port> 0 0 <payload_size>` to connect to the xxx bench_server in the example, such as the server started by `cargo run --release --all-features --example bench_async_server`.

I'll add a performance test document when ws-tool is stable, but sorry, I haven't had much time on this project lately.
