### ISSUE TITLE
Payload size causes weird performance variance

### ISSUE THREAD

**Issue by 0xZP** [PrivateRookie/ws-tool#19]
![image](https://user-images.githubusercontent.com/118121538/206821109-820b3e35-7628-4918-ad66-eaf2ac1ff8c2.png)
as the snapshot shows, when using load_test code from example with different payload size, got a very strange performance variance. I don't know what causes it but I think a 10KB payload should be the real use case instead uWebsocket's load_test default 1MB payload size.

**Comment by 0xZP** [comment]
![16KB_server](https://user-images.githubusercontent.com/118121538/206745927-7dbfcd61-19cf-4e28-9f67-b6d2437b83b2.svg)
![160KB_server](https://user-images.githubusercontent.com/118121538/206745937-c353418b-ff3f-44ff-8482-4a65be68fc94.svg)
server flamegraph when payload size is 16KB (above) and 160KB (below).

**Comment by PrivateRookie** [comment]
Sorry for the confusing example of load test in the examples, this example is intended to be improved after the simd and deflate features are implemented, so it is only a semi-finished product and cannot be used in performance testing. If you want to do a load test, I recommend the load_test program in [uWebSocket](https://github.com/uNetworking/uWebSockets/blob/c4d45fbf3d282bf68a3b44d6dcabad9414f49e84/benchmarks/Makefile), you can modify your own payload size and number of clients to simulate different loads

**Comment by 0xZP** [comment]
![image](https://user-images.githubusercontent.com/118121538/206826935-3e057475-cd64-4913-866b-ad2a58d9d0ba.png)

I found out it was because some tokio scheduler issue cause the stuck. this [pr](https://github.com/PrivateRookie/ws-tool/pull/20) can get right result but some time it still stuck...

**Comment by 0xZP** [comment]
![image](https://user-images.githubusercontent.com/118121538/206827037-2e012094-78f2-496c-8bd7-802000b2bd71.png)
If I increase the payload number, it becomes slower and slower, pretty weird...

**Comment by 0xZP** [comment]
> Sorry for the confusing example of load test in the examples, this example is intended to be improved after the simd and deflate features are implemented, so it is only a semi-finished product and cannot be used in performance testing. If you want to do a load test, I recommend the load_test program in [uWebSocket](https://github.com/uNetworking/uWebSockets/blob/c4d45fbf3d282bf68a3b44d6dcabad9414f49e84/benchmarks/Makefile), you can modify your own payload size and number of clients to simulate different loads

![image](https://user-images.githubusercontent.com/118121538/206827255-dfa53b66-633f-4646-aa49-d077e5117e37.png)

btw, if i use uWebSockets load_test, when payload small than 64KB it's still stuck.

seem is something wrong with my system (Linux 5.15.0-56-generic #62-Ubuntu )...

**Comment by PrivateRookie** [comment]
> 

when payload is less than 64kb, I stuck too, it seems like a limit of uWebSocket load test

**Comment by PrivateRookie** [comment]
After lunch time I will write a sync load test use multi thread, it may take some times.

**Comment by PrivateRookie** [comment]
> > Sorry for the confusing example of load test in the examples, this example is intended to be improved after the simd and deflate features are implemented, so it is only a semi-finished product and cannot be used in performance testing. If you want to do a load test, I recommend the load_test program in [uWebSocket](https://github.com/uNetworking/uWebSockets/blob/c4d45fbf3d282bf68a3b44d6dcabad9414f49e84/benchmarks/Makefile), you can modify your own payload size and number of clients to simulate different loads
> 
> ![image](https://user-images.githubusercontent.com/118121538/206827255-dfa53b66-633f-4646-aa49-d077e5117e37.png)
> 
> btw, if i use uWebSockets load_test, when payload small than 64KB it's still stuck.
> 
> seem is something wrong with my system (Linux 5.15.0-56-generic #62-Ubuntu )...

please run `git pull` and try new load_test example

**Comment by 0xZP** [comment]
![image](https://user-images.githubusercontent.com/118121538/206830182-a144c544-5a79-488e-8ea5-3c5dd8851312.png)
[new sync version load_test](https://github.com/PrivateRookie/ws-tool/commit/8d5211f2587cca9f97f50755adcac1a7982ff0b7) work as expect.

**Comment by 0xZP** [comment]
tungstenite-rs is faster in 16KB load_test in my machine. bench_tungstenite 32204.095 vs bench_async_server 28720.104 vs bench_server_split 26821.550

**Comment by PrivateRookie** [comment]
That's wired,  tungstenite example unwrap recv result while bench_server and bench_async_server will check recv result, if i remove check code and unwrap them like tungstenite example. ws-tools is faster.

load test options `--conn 1 -n 50000 -p 16`
my bench result
tungstenite: 27535.843
bench_server: 29187.466
bench_async_server: 28784.453
tungstenite:

**Comment by 0xZP** [comment]
```
    loop {
        let (stream, addr) = listener.accept().unwrap();
        stream.set_nodelay(true).unwrap();
        std::thread::spawn(move || {
            tracing::info!("got connect from {:?}", addr);
            let mut ws = tungstenite::accept(stream).unwrap();
            loop {
                if let Ok(msg) = ws.read_message() {
                    if msg.is_close() {
                        break;
                    } 
                    ws.write_message(msg).unwrap();
                } else {
                    break;
                }
            }
            tracing::info!("one conn down");
        });
    }
```
I changed tungstenite example to check recv result it still got ~32000+ 

```
Running `target/release/examples/load_test 'ws://127.0.0.1:9000' -c 1 -p 16 -n 50000`
2022-12-10T07:48:56.267408Z  WARN ws_tool::blocking: setting tls cert has no effect on insecure ws
[000 - OK] 32631.024
```

**Comment by PrivateRookie** [comment]
what's your benchmark machine and ip network kernel setting?

**Comment by 0xZP** [comment]
Intel Xeon Gold 6230 (80) @ 2.1GHz

force_latency=cstate.id:1|3
governor=performance
energy_perf_bias=performance
min_perf_pct=100
kernel.sched_min_granularity_ns=3000000
kernel.sched_wakeup_granularity_ns=4000000
vm.dirty_ratio=10
vm.dirty_background_ratio=3
vm.swappiness=10
kernel.sched_migration_cost_ns=5000000
net.core.busy_read=50
net.core.busy_poll=50
net.ipv4.tcp_fastopen=3
kernel.numa_balancing=0
cmdline_network_latency=skew_tick=1
net.ipv4.ip_forward=1
net.core.default_qdisc=cake
net.ipv4.tcp_congestion_control=bbr
net.ipv4.tcp_slow_start_after_idle=0
net.ipv4.tcp_notsent_lowat=16384

**Comment by 0xZP** [comment]
8KB payload result:
bench_server: 33021.222
bench_server_split: 32834.431
bench_tungstenite: 39017.241
bench_async_server: 33839.912

**Comment by 0xZP** [comment]
![server](https://user-images.githubusercontent.com/118121538/206861240-0a40d264-ecd2-4cfb-96a8-f80785c6cd48.svg)
![tungstenite](https://user-images.githubusercontent.com/118121538/206861250-7f6ec71e-6400-40bd-af06-413598d0b3a8.svg)
8KB payload bench_server (above) and bench_tungstenite (below) flamegraph.

**Comment by PrivateRookie** [comment]
It seems that ws-tool can operate buffered writer/reader when the payload is small, instead of directly operating the raw tcpstream, but this may cause higher latency, which needs more profiles to be sure. Perhaps it is possible to change the S in WsStream from tcpstream to BufferedStream without changing any code, which can be implemented in the factory function of the accept/connect function params
