### ISSUE TITLE
permessage-deflate extension support

### ISSUE THREAD

**Issue by PrivateRookie** [PrivateRookie/ws-tool#22]
[RFC](https://datatracker.ietf.org/doc/html/rfc7692)

**Comment by fnordpig** [comment]
Hi!  I'm in need of a high performance websocket impl and have been kicking the tires on ws-tool, but just hit a websocket api that requires deflate. I'd contribute to this but I'm a late term newbie to rust and I'm afraid I'd only hinder your mojo.

**Comment by PrivateRookie** [comment]
I am implementing this feature recently, but since the deflate algorithm implemented in pure rust does not have the required parameters for permessage-deflate extension, it can only be bound with libz, which will cause ws-tool fail to compile without system dependencies, so I am still considering whether to re-implement the deflate algorithm; in addition, the implementation of permessage-delate in different language is slightly different, and I prefer to follow browser implementation. Anyway, feel free to fork this repo and make PR

**Comment by PrivateRookie** [comment]
An experimental per message deflate implementation has been implemented in #24
