### ISSUE TITLE
大佬，不会是因为找不到带代理功能的rust websocket库就自己写一个来连币安吧

### ISSUE THREAD

**Issue by malongshuai** [PrivateRookie/ws-tool#7]
看到大佬的这个库和bian-rs，于是有此联想。祝发财，祝翻100倍，哈哈。

**Comment by PrivateRookie** [comment]
最开始确实是因为找不到支持代理的websocket库, 我fork一个分支实现功能后他们不接受PR, 而且他们API我用着不习惯, 干脆自己写一个.
